### ISSUE TITLE
Update @angular dependency to 10.0

### ISSUE THREAD

**Issue by macfurin** [ashley-hunter/ng-heroicons#1]
Hello Ashley, thanks for your great lib.

Could you update  projects `package.json` to depend on @angular@^10.0.0 like you did in root `package.json` ?

https://github.com/ashley-hunter/ng-heroicons/blob/1be92a0c1264ab207120f21caa27f3ef3effbf54/projects/ng-heroicons/package.json#L9-L11

Thanks,

Vincent

**Comment by ashley-hunter** [comment]
Apologies, I only noticed this issue now. I have updated the version ranges now. Thanks!
